### ISSUE TITLE
Docs request: what exactly does it do?

### ISSUE THREAD

**Issue by Richie-Peak** [M7mdisk/obsidian-gpt#4]
Hi, there are lots of Obsidian plugins that use GPT and embeddings and its hard to tell which one is useful for which use case. Could you flesh out a bit more what exactly the app does?

**Comment by M7mdisk** [comment]
This plugin gives you an assistant that can answer questions from _your notes_ and only your notes. 
Basically chatGPT but the knowledge base is your notes.

closed because its not an issue.
